server:
  port: 8084
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payments_async
    username: postgres
    password: guluzada120912
  liquibase:
    change-log: classpath:liguibase/changelog-master.yml
